eclipse-dataspace-protocol-base/DataspaceProtocol

- .github/workflows/autopublish.yaml
- catalog/catalog.binding.https.md
- index.html
- negotiation/contract.negotiation.binding.https.md
- negotiation/contract.negotiation.protocol.md
- transfer/transfer.process.binding.https.md
- transfer/transfer.process.protocol.md
This PR adds the last necessary changes to fix all links in the respec-based website rendering.
Currently, a lot of the features making respec a great tool aren't yet used. This PR edits the md files in such a way that changes. Here's a preview: https://arnoweiss.github.io/DataspaceProtocol/
Closes #6
> chore: finish initial respec deployment

- artifacts/src/main/resources/catalog/catalog-request-message-schema.json
- artifacts/src/main/resources/catalog/example/catalog-request-message.json
- artifacts/src/test/java/org/eclipse/dsp/context/catalog/CatalogContextTest.java
- artifacts/src/test/java/org/eclipse/dsp/schema/catalog/CatalogRequestMessageSchemaTest.java
add some more artifacts
fixes #68 
> fix: add artifacts for catalog request message

- artifacts/buildSrc/README.md
- artifacts/buildSrc/build.gradle.kts
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/SchemaTableGeneratorPlugin.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/SchemaTableGeneratorPluginExtension.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/ElementDefinition.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/JsomParser.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/JsonSchemaKeywords.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/JsonTypes.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/SchemaModel.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/SchemaModelContext.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/SchemaProperty.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/SchemaPropertyReference.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/jsom/SchemaType.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/transformer/HtmlTableTransformer.java
- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/transformer/SchemaTypeTransformer.java
- artifacts/buildSrc/src/test/java/org/eclipse/dsp/generation/jsom/JsomParserTest.java
- artifacts/buildSrc/src/test/java/org/eclipse/dsp/generation/jsom/SchemaModelContextTest.java
- artifacts/buildSrc/src/test/java/org/eclipse/dsp/generation/jsom/SchemaTypeTest.java
- artifacts/buildSrc/src/test/java/org/eclipse/dsp/generation/jsom/TestSchema.java
- artifacts/buildSrc/src/test/java/org/eclipse/dsp/generation/transformer/HtmlTableTransformerTest.java
This PR generates HTML tables containing relevant type information (e.g., required and optional properties) for all DSP messages. The HTML tables are generated by a custom Gradle Plugin that parses the DSP schemas at build-time. The generated tables may then be directly included in ReSpec markdown.
The PR introduces the plugin and Json Schema Object Model parser thatis used to generate the tables. Subsequent PRs will include the generated tables in the specification text and remove the relevant PNG images and manually-created type information.   
Support for `$comment` or `description` still needs to be added. That can be done in another PR.
The plugin could be enhanced to provide hyperlinks for referenced type information. For example, a `MessageOffer` references the `Offer` type. The …
> feat: Add support for message type generation from Json schemas

- artifacts/src/main/resources/catalog/dataset-schema.json
- artifacts/src/test/java/org/eclipse/dsp/schema/catalog/DatasetSchemaTest.java
The `Dataset` schema for dataset response messages does not contain an `@context` constraint. This is fixed by introducing a `RootDataset` type similar to `RootCatalog` that requires `@context` for use in response messages. However, when a dataset is contained in a catalog, the original `Dataset` type is used without `@context`.
Closes #80
> fix: Fixes the dataset type to include a `@context`

- specifications/model/model.md
- specifications/model/terminology.md
changed Dataspace Authority to Dataspace Governance Authority to align with the community terminology
The wider Dataspace community has converged on using Dataspace Governance Authority (short DSGA) instead of Dataspace Authority
> chore: change Dataspace Authority to Dataspace Governance Authority to align with the community terminology

- specifications/common/common.protocol.md
Adds statement that the http version endpoint is unprotected.
A client can't know how to authenticate against the protocol endpoint.
closes #95
> feat: clarify that version-endpoint is unprotected

- specifications/model/model.md
This turned out to be a typo.
Closes #43 
> fix: typo in catalog-dataset-target relation

- specifications/catalog/catalog.binding.https.md
- specifications/common/scope.md
- specifications/model/model.md
- specifications/negotiation/contract.negotiation.protocol.md
This PR clarifies the (lack of) dependence of the DSP on the DCAT and ODRL vocabularies.
Since the json-schemas are the sole normative source for message structure, the external pointers are no longer providing any benefit.
Closes #78
> fix: remove normative references to ODRL and DCAT

- specifications/negotiation/contract.negotiation.binding.https.md
Adds GET negotiations/:consumerPid endpoint to negotiation binding.
Both parties should be able to request a negotiation object - either by consumer or provider PID.
--
Closes #39
> feat: add GET negotiations/:consumerPid endpoint to negotiation binding

- specifications/catalog/catalog.binding.https.md
- specifications/common/common.protocol.md
- specifications/negotiation/contract.negotiation.binding.https.md
- specifications/transfer/transfer.process.binding.https.md
Cleans up section headings for a better readability of ToC and binding documents.
Unnessessary duplicated information. Alignment with message section.
Now:
Then:
--
Closes # <-- _insert issue number if one exists_
> refactor: improve readability of ToC and bindings

- artifacts/src/main/resources/catalog/catalogservice-did-service-schema.json
- artifacts/src/main/resources/catalog/example/catalogservice-did-service.json
- artifacts/src/main/resources/context/dspace.jsonld
- specifications/catalog/catalog.protocol.md
- specifications/common/common.protocol.md
The PR changes the definition of the well-known http versioning endpoint in a non-compatible manner and adds (building on that) normative statements how to publicize a `CatalogService` in a did document. 
Reasons are laid out in the ticket.
The did-core standard was added as an informative reference. There are no automated tests for json/json-ld-compatibility and deserialization as those are concerns for the did-spec.
Closes #44
> feat: add did doc registration and align well-known version endpoint

- artifacts/buildSrc/src/main/java/org/eclipse/dsp/generation/transformer/HtmlTableTransformer.java
- artifacts/src/main/resources/transfer/data-address-schema.json
- index.html
- specifications/common/type-definitions.md
add the pipeline generated tables to a new section in the annex. The generation logic was updated so that links are built automatically. This also required the refactoring of the dataaddress schema.
readability
Closes #82
> chore: add lower-level type definitions table to annex

- index.html
Change "International Dataspaces Association" to "International Data Spaces Association"
The name of the organisation is fixed.
Amends #118
> docs: fix author section

- .github/scripts/checkout-tags.sh
- .github/scripts/index.html
- index.html
- specifications/catalog/catalog.protocol.md
- specifications/common/type.definitions.md
This PR publishes a separate github page for the current state of the spec as a first Release Candidate for version `2025-1`.
Lots of new features.
**There is further action required from the committer who merges this PR.**
Github does not allow to merge tags via PRs. Every committer however can push tags to main. After merging this PR, a committer must:
1. create a tag called `2025-1-RC1` on commit [d8f6428a1b7a9a9be13719c226eaa8d9cbb5adc9](https://github.com/eclipse-dataspace-protocol-base/DataspaceProtocol/commit/d8f6428a1b7a9a9be13719c226eaa8d9cbb5adc9) and push if done in IDE.
2. rerun all github actions.
This will lead to a setup like in my fork:
https://arnoweiss.github.io/DataspaceProtocol/
https://arnoweiss.github.io/DataspaceProtocol/2025-1-RC1/ …
> chore: publish version `2025-1-RC1`

- artifacts/src/main/resources/common/example/protocol-version.json
- artifacts/src/main/resources/common/protocol-version-schema.json
- artifacts/src/test/java/org/eclipse/dsp/schema/common/InvalidVersionSchemaTest.java
- specifications/common/common.protocol.md
- specifications/common/type.definitions.md
This PR changes the setup of the common versioning endpoint.
1. Restrict versioning-endpoint to HTTPS across bindings
Even in a distant future when there may be different bindings for DSP messages, it is reasonable to expect that the well-known HTTPS endpoint will be queried for which endpoints are relevant. A consumer has to start somewhere and it cannot be assumed that the DSP-binding a Provider uses is necessarily known.
2. Add the `auth` and `binding` properties
The `auth` property holds a string telling the Consumer how to authenticate to the Provider's DSP endpoints. This is necessary, especially if the catalog-endpoints are protected already. The `binding` property describes the DSP-protocol binding so the Consumer knows not just WHERE to ask but also HOW. This is relevant for …
> feat: upgrade version endpoint

- artifacts/src/main/resources/common/protocol-version-schema.json
Outlines how published DSP versions should be referred to in the version endpoint.
consistency 
for forward compatibility with future versions, see issue
Closes #152
> chore: enumerate dsp-versions

- specifications/catalog/catalog.protocol.md
Normative statements on the nature of the `DataService.endpointURL`
clarity
Closes #145 
> feat: detail out endpointURL

- artifacts/src/main/resources/catalog/dataset-schema.json
remove the duplicate `@id` property
redundancy removal
build succeeds locally
Closes #140
> fix: remove duplicate id property on DataService

- specifications/common/introduction.md
- specifications/common/scope.md
- specifications/common/terminology.md
Adds "data transfer protocol" to terms and definitions.
Increase the comprehensibility of the documents by explaining used terms. Emphasize the delimitation of the DSP from the data layer.
Closes #132
> chore: add "data transfer protocol" to terms and definitions

- artifacts/src/main/resources/negotiation/contract-request-message-schema.json
- artifacts/src/main/resources/negotiation/contract-schema.json
- artifacts/src/test/java/org/eclipse/dsp/schema/negotiation/ContractRequestMessageSchemaTest.java
- artifacts/src/test/java/org/eclipse/dsp/schema/negotiation/InvalidContractRequestMessageSchemaTest.java
- specifications/negotiation/contract.negotiation.binding.https.md
- specifications/negotiation/contract.negotiation.protocol.md
This PR narrows down the allowed data structure in the `offer` property of the `ContractRequestMessage`
A client has no way of knowing if a provider's ParticipantAgent requires a policy of just the id advertised in the catalog. That's why the Consumer must always give the full object anyway.
How a Provider handles the message is outside the scope of the spec.
Closes #142 
> feat: restrict contract request message to object

- artifacts/src/main/resources/catalog/example/catalog.json
- artifacts/src/main/resources/context/odrl.jsonld
- artifacts/src/main/resources/negotiation/contract-schema.json
- artifacts/src/main/resources/negotiation/example/contract-agreement-message-full.json
- artifacts/src/test/java/org/eclipse/dsp/schema/negotiation/PolicySchemaTest.java
Changes `duty` property to be always an array.
Allow flexibility with respect to ODRL policies.
Closes #157
> feat: change duty from single element to array

- specifications/common/common.protocol.md
Clear difference between `<root>` and `<base>` URLs.
Currently the versioning endpoint sits on a subpath of `<base>` which is plain wrong.
Closes #177
> fix: clearly differentiate between base and root URLs

- artifacts/buildSrc/README.md
- artifacts/buildSrc/src/test/java/org/eclipse/dsp/generation/jsom/TestSchema.java
- artifacts/src/main/resources/negotiation/contract-schema.json
- artifacts/src/test/java/org/eclipse/dsp/schema/negotiation/PolicySchemaTest.java
- specifications/common/type.definitions.md
Adds definition of prohibition to schemas. Unifies `permission` and `prohibition` to `Rule`.
Prohibitions objects are not modelled in the JSON schemas, but are referenced as properties.
--
Closes #162
> feat: add definition of Rule to schemas

- specifications/common/common.protocol.md
This PR notes the possibility for term collisions between profiles.
There's a non-trivial risk of DSP-profiles defining terms resolving to diverging URIs. This is alluded to in the spec and will be elaborated in the best practices.
Closes #158
Created follow-up in best practices: https://github.com/eclipse-dataspace-protocol-base/dsp_best_practices/issues/17
> chore: elaborate on json-ld context extension

- artifacts/src/main/resources/common/example/protocol-version.json
- artifacts/src/main/resources/common/protocol-version-schema.json
- specifications/common/common.protocol.md
- specifications/common/type.definitions.md
adds an additional property to the versions document to signify the type of id participants go by.
Participants must know before initiating communication how to refer to one another. The base spec only defines the `participantId`, `assigner` and `assignee` properties as strings. Profiles must build on top of that
Closes #166
> feat: add signal for participant identification

- artifacts/src/main/resources/common/protocol-version-schema.json
- artifacts/src/main/resources/negotiation/contract-schema.json
- artifacts/src/test/java/org/eclipse/dsp/context/fixtures/AbstractJsonLdTest.java
- artifacts/src/test/java/org/eclipse/dsp/schema/common/InvalidVersionSchemaTest.java
- artifacts/src/test/java/org/eclipse/dsp/schema/fixtures/AbstractSchemaTest.java
1. assert that json schemas comply to the meta schema
2. execute test suite on the meta schema release used in the schemas' `"$schema"` property (`"https://json-schema.org/draft/2019-09/schema"`)
3. fix two bugs in the schemas
functional correctness
Closes #208
Closes #210
> fix: invalid schemas, test suite

- index.html
removes templated comments
correctness wrt process
Closes #214
> fix: remove accidental references to W3C processes

- artifacts/src/main/resources/catalog/example/dataset.json
- artifacts/src/main/resources/negotiation/example/contract-offer-message_initial.json
The PR removes two instances of the `assigner` property from examples where they're not in the schemas.
consistency 
The schemas permit additional properties - that's why testing didn't catch this.
Closes #213
> fix: remove assigner property from examples where appropriate

- artifacts/src/main/resources/catalog/catalog-schema.json
- artifacts/src/main/resources/catalog/dataset-schema.json
- specifications/catalog/catalog.protocol.md
- specifications/common/type.definitions.md
Readds optional property previously erroneously removed
Closes #219
> fix: readd `distribution` to `Catalog`
